### ISSUE TITLE
bitflags FontStyle attributes are private

### ISSUE THREAD

**Issue by Cobrand** [andelf/rust-sdl2_ttf#34]
On the examples/demo.rs file, replace line 61 by 
```rust
let mut font = ttf_context.load_font(font_path, 128).unwrap();
font.set_style(sdl2_ttf::font::STYLE_BOLD);
```

This error occurs :  ```examples/demo.rs:62:20: 62:46 error: const `STYLE_BOLD` is private```

This bug is to be expected, as it is explicitly stated in the [documentation of bitflags](https://doc.rust-lang.org/bitflags/bitflags/macro.bitflags!.html#visibility)

Now to add "pub" before the struct we must update bitflags to 0.5, (and change some compatibility issues), but even though FontStyle is public after these changes, the same error happens.

I suspect a bug on the bitflags crate side, but I might be mistaken.

**Comment by andelf** [comment]
``STYLE_*`` const should be ``pub use``-ed in ``lib.rs``

try use:
```rust
let mut font = ttf_context.load_font(font_path, 128).unwrap();
font.set_style(sdl2_ttf::STYLE_BOLD);
```
