### ISSUE TITLE
Move rust-sdl_ttf in rust-sdl2

### ISSUE THREAD

**Issue by Cobrand** [andelf/rust-sdl2_ttf#48]
Explained here AngryLawyer/rust-sdl2#564

This is used both as a reference from here to the other topic, and a request for approval from @andelf 

@andelf Could you please tell us here or in the other issue if you agree with this or not ?

**Comment by andelf** [comment]
I totally agree.

**Comment by andelf** [comment]
I've commented on AngryLawyer/rust-sdl2#564
